Update what-is-an-operator.md
metal3-io/metal3-io.github.io pull request #248
Opened 2022-11-15 08:53 UTC by kaovilai

2023-02-09 11:08 UTC, tuminoid requested changes

2023-02-09 16:23 UTC, kaovilai commented on _faqs/what-is-an-operator.md
> +An Operator is a method of packaging, deploying and managing a Kubernetes application. A Kubernetes application is an application that is both deployed on Kubernetes and managed using the Kubernetes
```suggestion
An Operator is a method of packaging, deploying and managing a Kubernetes application. A Kubernetes application is an application that is both deployed on Kubernetes and managed using the Kubernetes APIs and kubectl tooling. You can think of Operators as the runtime that manages this type of application on Kubernetes. If you want to learn more about Operators you can check the Operator framework website [https://operatorframework.io/what/](https://operatorframework.io/what/)
```

2023-02-09 16:34 UTC, tuminoid commented
Thanks. We need to fix the deploy tests, but LGTM now.

2023-02-10 07:23 UTC, tuminoid commented
@kaovilai the test deploy is fixed. Could you rebase?

2023-02-13 21:21 UTC, kaovilai commented
"This branch has no conflicts with the base branch"

Don't see any indication of rebase required?

2023-02-13 21:22 UTC, kaovilai commented
I guess to retrigger deploy.. ok

2023-02-14 08:05 UTC, tuminoid commented
Rebase was to the checks working in this PR. Please squash the commits and were good to merge.

2023-03-02 09:40 UTC, tuminoid requested changes
Commit squashing required.

2023-03-02 17:22 UTC, kaovilai commented
github should've figured out a button for this in web ui by now.

2023-03-06 13:42 UTC, tuminoid approved these changes
LGTM.

/cc @Rozzii @lentzi90

2023-03-08 06:15 UTC, lentzi90 approved these changes
/approve

2023-03-17 09:27 UTC, tuminoid reviewed
/lgtm

2023-03-17 09:33 UTC, tuminoid commented
/retest

2023-03-17 11:39 UTC, kashifest commented
/hold

2023-03-17 11:51 UTC, kashifest commented
/hold cancel

2023-03-17 11:59 UTC, merged