Blog section update
metal3-io/metal3-io.github.io pull request #320
Opened 2023-07-03 02:51 UTC by SafeEHA

Changed the position and style of the blog section

2023-07-05 15:12 UTC, elfosardo requested changes
please remove all the indentation or code style changes

2023-07-05 15:12 UTC, elfosardo commented on _sass/_homepage.scss
> +          width: auto;
remove indentation change

2023-07-06 04:55 UTC, hroyrh commented on index.html
> +    <div class="mk-blog-meta__preview__scroll-wrapper">
Can you add a single line space before the div block

2023-07-07 06:52 UTC, hroyrh commented
/lgtm

2023-07-07 09:23 UTC, hroyrh commented
/approve

2023-07-07 09:23 UTC, merged